port: ":1323"

db: 
  driver: "mysql"
  username: "root"
  password: "example"
  connection: "tcp"
  host: "localhost"
  port: "3306"
  dbname: "chat" 


# db: 
#   driver: "mysql"
#   username: "root"
#   password: "example"
#   connection: "tcp"
#   host: "db"
#   port: "3306"
#   dbname: "chat" 